#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /config/keys &> /dev/null

SUBJECT="/C=./ST=./L=./O=./OU=./CN=."
if [[ -f /config/keys/cert.key && -f /config/keys/cert.crt ]]; then
    echo "using keys found in /config/keys"
else
    echo "generating self-signed keys in /config/keys, you can replace these with your own keys if required"
    rm -f \
        /config/keys/cert.key \
        /config/keys/cert.crt || true
    openssl req -new -x509 -days 3650 -nodes -out /config/keys/cert.crt -keyout /config/keys/cert.key -subj "$SUBJECT"
fi

# permissions
lsiown -R abc:abc \
    /config \
    /etc/ntfy
